name: "build"
on:
  push:
    branches:
    - "!dependabot/*"
    - "*"
  pull_request:
    branches:
    - "*"
jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        java: [ 8, 11, 16 ]
    name: "Java ${{ matrix.java }} Build"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-java@v2"
      with:
        distribution: "adopt"
        java-package: "jdk"
        java-version: "${{ matrix.java }}"
    - uses: "gradle/wrapper-validation-action@v1"
    - name: "Gradle Build"
      run: "./gradlew build"
