name: "Publish to Maven"
on:
  push:
    tags:
    - '*'
jobs:
  publish:
    name: "Publish to Maven"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-java@v2"
    - name: "Gradle Build"
      run: "./gradlew build"
    - name: "Gradle Publish"
      run: "./gradlew publish"
    - name: "Publish to Sonatype"
      run: "ORG_GRADLE_PROJECT_release=${GITHUB_REF#ref/tags/} ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository"
