name: "Publish to Maven"
on:
  push:
    tags:
    - '*'
jobs:
  publish:
    name: "Publish to Maven"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "actions/setup-java@v2"
      with:
        distribution: "adopt"
        java-package: "jdk"
        java-version: "11" # LTS
    - uses: "bufbuild/buf-setup-action@v0.2.0"
      with:
        version: "0.43.2"
    - name: "Publish to Sonatype"
      env:
        ORG_GRADLE_PROJECT_signingKey: "${{ secrets.SIGNING_KEY_ARMORED }}"
        ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.SIGNING_PASSWORD }}"
        ORG_GRADLE_PROJECT_sonatypeUsername: "${{ secrets.SONATYPE_USERNAME }}"
        ORG_GRADLE_PROJECT_sonatypePassword: "${{ secrets.SONATYPE_PASSWORD }}"
      run: "ORG_GRADLE_PROJECT_release=${GITHUB_REF#ref/tags/} ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository"
